### PR TITLE
List Peppol Registrations

### PR DESCRIPTION
**Pull request by stephdewit**

### CODE REVIEW

**Review by damienbr — APPROVED** [review]
Is it a breaking change?

**Comment by stephdewit** [comment]
> Is it a breaking change?

No, I don't think so, only added stuff. Is there something making you think it is?

**Comment by damienbr** [comment]
this change
image

**Comment by stephdewit** [comment]
Existing methods returning a `PaginatedCollection` will still return the object with the `Items` property, so I don't think it's a breaking change.

I had to extract the base class because _Registrations_ is the first collection without paging I had to implement.

**Pull request merged**
